export default {
  REPOSITORIES_LIST_REQUESTED: 'REPOSITORIES_LIST_REQUESTED',
  REPOSITORIES_LIST_FULFILLED: 'REPOSITORIES_LIST_FULFILLED',
  REPOSITORIES_LIST_FAILD: 'REPOSITORIES_LIST_FAILD',

  USER_STARTED_TYPE: 'USER_STARTED_TYPE',
  GO_TO_PAGE_ACTION: 'GO_TO_PAGE_ACTION',
  UPDATE_DURATION_TIME: 'UPDATE_DURATION_TIME',

  NAVIGATION_ACTION: 'NAVIGATION_ACTION',

  REPOSITORY_DETAILS_REQUESTED: 'REPOSITORY_DETAILS_REQUESTED',
  REPOSITORY_DETAILS_FULFILLED: 'REPOSITORY_DETAILS_FULFILLED',
  REPOSITORY_DETAILS_FAILD: 'REPOSITORY_DETAILS_FAILD',

  REPOSITORY_READ_ME_REQUESTED: 'REPOSITORY_READ_ME_REQUESTED',
  REPOSITORY_READ_ME_FULFILLED: 'REPOSITORY_READ_ME_FULFILLED',
  REPOSITORY_READ_ME_FAILD: 'REPOSITORY_READ_ME_FAILD',

  BRIEF_RESULTS_REMOVED: 'BRIEF_RESULTS_REMOVED',
};
